// <auto-generated />
namespace Sediin.PraticheRegionali.DOM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EBT_tableCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EBT_tableCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "202411220915322_EBT_tableCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
